const tasks = [
  {
    id: 1,
    title: 'Walk my golden retriever for 30 mins',
    description:
      "Need someone to walk Max around the neighborhood while I'm in a meeting. He's very friendly and well-behaved.",
    location: 'Downtown Seattle',
    distance: '0.8 miles',
    duration: '30 mins',
    payment: '$15',
    category: 'Pet Care',
    urgent: true,
    postedBy: 'Sarah M.',
    rating: 4.9,
    remote: false,
  },
  {
    id: 2,
    title: 'Translate email from Spanish to English',
    description:
      'Quick translation needed for business email, about 200 words. Native Spanish speaker preferred.',
    location: 'Remote',
    distance: 'Remote',
    duration: '15 mins',
    payment: '$12',
    category: 'Translation',
    urgent: false,
    postedBy: 'Mike R.',
    rating: 4.8,
    remote: true,
  },
  {
    id: 3,
    title: 'Pick up documents from office',
    description:
      'Need someone to collect signed contracts from downtown office and drop them at FedEx.',
    location: 'Financial District',
    distance: '1.2 miles',
    duration: '45 mins',
    payment: '$25',
    category: 'Errands',
    urgent: true,
    postedBy: 'Jennifer L.',
    rating: 5.0,
    remote: false,
  },
  {
    id: 4,
    title: 'Proofread blog post (500 words)',
    description:
      'Looking for someone to proofread and edit a blog post about sustainable living.',
    location: 'Remote',
    distance: 'Remote',
    duration: '20 mins',
    payment: '$18',
    category: 'Writing',
    urgent: false,
    postedBy: 'Alex K.',
    rating: 4.7,
    remote: true,
  },
  {
    id: 5,
    title: 'Assemble IKEA bookshelf',
    description:
      'Need help assembling a medium-sized bookshelf. All tools provided.',
    location: 'Capitol Hill',
    distance: '2.1 miles',
    duration: '60 mins',
    payment: '$35',
    category: 'Assembly',
    urgent: false,
    postedBy: 'David P.',
    rating: 4.9,
    remote: false,
  },
  {
    id: 6,
    title: 'Data entry from receipts',
    description:
      'Enter data from 20 receipts into a spreadsheet. Template provided.',
    location: 'Remote',
    distance: 'Remote',
    duration: '25 mins',
    payment: '$20',
    category: 'Data Entry',
    urgent: false,
    postedBy: 'Lisa W.',
    rating: 4.6,
    remote: true,
  },
];

export { tasks };
